# Generated by Django 4.1.7 on 2023-03-10 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catBreeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catbreed',
            old_name='name',
            new_name='breed',
        ),
        migrations.AddField(
            model_name='catbreed',
            name='adaptability',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='affectionLevel',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='childFriendly',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='grooming',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='healthIssues',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='intelligence',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='lifeSpan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='otherPhotos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='socialNeeds',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='catbreed',
            name='strangerFriendly',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='catbreed',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='catbreed',
            name='temperament',
            field=models.CharField(max_length=150),
        ),
    ]
